# Introdução {#intro}

À acessibilidade são frequentemente atribuídos diferentes significados, a depender da forma como é operacionalizada e do contexto em que é analisada [@geurs2004accessibility; @kwan1998spacetime; @vanwee2016accessible]. Em linhas gerais, no entanto, pode se dizer que a acessibilidade é determinada pela distribuição espacial de atividades, ou de potenciais oportunidades, e pela facilidade pelas quais elas podem ser acessadas [@handy1997measuring].

Estudos recentes levam ao entendimento de que maiores níveis de acessibilidade se traduzem em maiores potenciais de realização e satisfação pessoal [@martens2012justice], e de que políticas de transporte devem conferir níveis mínimos de acessibilidade a determinados destinos e reduzir desigualdades de acesso a oportunidades [@pereira2017distributive]. A acessibilidade, portanto, vem cada vez mais sendo considerada um objetivo de políticas de transporte nos últimos anos [@neutens2010equity; @vanwee2016accessible], o que tem levado pesquisadores e tomadores de decisão a investigar como essas políticas afetam de forma distinta a acessibilidade de diferentes localidades e grupos socioeconômicos [@lucas2016method].

As estimativas dos níveis de acesso a oportunidades de um indivíduo ou local podem ser feitas através de diversas medidas, sendo estas classificadas em diferentes grupos, conforme a perspectiva que adotam ao medir a acessibilidade [@geurs2004accessibility]. Dentre esses grupos, um dos mais frequentemente utilizados no planejamento urbano e de transportes é o de medidas baseadas em localidades, que se diferencia dos demais ao associar a acessibilidade a um lugar, e não a um indivíduo ou atividade [@miller2007placebased].

As medidas desse grupo atribuem a cada deslocamento um fator de impedância que pode ser expresso em forma de tempo, distância, dinheiro ou alguma outra função de desutilidade. Via de regra, no entanto, a maioria dos estudos que usam essas medidas estima a acessibilidade considerando apenas os custos de tempo de viagem [@el-geneidy2016cost; @venter2016assessing], embora idealmente todos os custos associados a um deslocamento devam ser adequadamente representados, como, por exemplo, os relacionados ao conforto, à conveniência e ao valor monetário de uma viagem [@bocarejo2014innovative; @dalvi1976measurement].

O custo monetário, em particular, é especialmente relevante para análises de políticas de transporte: primeiramente, porque muitas pessoas têm dificuldade de arcar com os custos dos deslocamentos cotidianos nos grandes centros urbanos, sejam estes tidos como desenvolvidos ou em desenvolvimento [@venter2011transport]; em segundo lugar, mais especificamente para análises relacionadas ao transporte público, porque o preço de uma viagem pode variar conforme fatores como a linha, o modo de transporte e o operador do serviço, não sendo, portanto, linearmente correlacionado ao usualmente representado tempo de viagem [@venter2016assessing]; e porque, no caso em que serviços similares são oferecidos a preço distintos, indivíduos de baixa renda podem acabar relegados a viagens mais baratas e potencialmente menos confiáveis [@conway2019getting].

Consequentemente, custos monetários vêm recebendo cada vez mais atenção na literatura de acessibilidade [e.g. @guzman2018accessibility; @liu2020measuring; @oviedo2019bus]. A maior parte dos estudos que consideram esses custos se concentra em como introduzi-los a medidas de acessibilidade para posteriormente diagnosticar desigualdades relacionadas aos transportes [e.g. @bocarejo2014innovative; @el-geneidy2016cost; @ma2017modeling]. Até o momento, no entanto, nenhum trabalho investigou de que forma a incorporação do custo monetário a medidas de acessibilidade afeta os resultados e conclusões derivadas de análises de acessibilidade e equidade nos transportes; ou seja, como os resultados de análises que consideram este custo se diferenciam daqueles que provêm de análises que não o consideram. Este trabalho visa preencher essa lacuna.

Esta dissertação se apoia sobre um estudo de caso que analisa a distribuição da acessibilidade ao emprego por transporte público na cidade do Rio de Janeiro. O Rio tem recebido, recentemente, bastante atenção de pesquisadores preocupados com questões relacionadas à equidade e à justiça em seus sistemas de transportes e uso do solo [e.g. @barboza2021balancing; @carneiro2019espraiamento; @pereira2018transport; @pereira2019distributional]. Ainda assim, até então nenhum trabalho que tenha a cidade como plano de fundo levou em consideração restrições monetárias em suas estimativas de acessibilidade. A introdução do custo monetário a uma análise de acessibilidade neste contexto, portanto, potencialmente destaca e revela desigualdades de acesso a oportunidades até então não identificadas em estudos prévios.

## Problema de pesquisa e hipóteses

Frente ao contexto apresentado, surge a seguinte pergunta, a partir da qual se elabora o problema de pesquisa:

- A incorporação do custo monetário a medidas de acessibilidade afeta os resultados e conclusões derivadas de análises de acessibilidade e equidade nos transportes? Caso positivo, como?

A partir deste problema, tem-se como hipótese básica:

- Por se tratar de um custo não necessariamente correlacionado com elementos normalmente incorporados ao fator de impedância de medidas de acessibilidade (principalmente o tempo de viagem), a incorporação do custo monetário a estas medidas afeta os resultados e conclusões derivadas de análises de acessibilidade e equidade.

De forma semelhante, tem-se como hipótese secundária:

- A incorporação do custo monetário a medidas de acessibilidade não necessariamente torna a distribuição da acessibilidade mais ou menos equitativa; como o custo monetário afeta essa distribuição depende em larga escala de elementos como políticas tarifárias, características operacionais e espaciais da rede de transporte público, e da co-distribuição espacial da população e das oportunidades.

## Objetivos

Alinhado ao problema destacado, configura-se como objetivo primário da pesquisa:

- Avaliar como a incorporação de restrições de custo monetário a medidas de acessibilidade impacta análises de equidade baseadas na distribuição da acessibilidade.

Os objetivos secundários, complementares ao primário, são:

- Identificar quais elementos dos sistemas de transportes e uso do solo exercem influência sobre a forma como restrições monetárias impactam análises de equidade e acessibilidade;

- Identificar como a incorporação do custo monetário a estimativas de acessibilidade pode complementar o diagnóstico das desigualdades de acesso a oportunidades no Rio de Janeiro, assim como propostas de políticas que derivem dele.

## Estrutura da dissertação

Este trabalho está dividido em seis capítulos. O segundo, que segue a introdução, apresenta uma discussão sobre medidas de acessibilidade, que culmina na escolha da utilizada no estudo de caso, e uma revisão de estudos que incorporaram o custo monetário a essas medidas. 

O terceiro descreve o método utilizado para estimar os níveis de acessibilidade e desigualdade nesta pesquisa, comparando as diversas escolhas metodológicas feitas ao longo do trabalho com boas práticas recomendadas na literatura. 

O quarto faz uma apresentação dos sistemas de transportes e uso do solo da cidade do Rio de Janeiro e de algumas variáveis socioeconômicas de sua população, para que no quinto sejam exibidos e discutidos os resultados do estudo de caso. 

As considerações finais são feitas no sexto capítulo. Nele são destacadas as contribuições deste trabalho, tanto as de natureza metodológica quanto as relevantes para o diagnóstico das desigualdades de acesso a oportunidades no Rio. Também são apresentadas as limitações da pesquisa e feitas recomendações para estudos futuros.